typedef unsigned char uint8_t;

// Generated by the unholy source of chatGPT
unsigned char reverseBits(unsigned char num) {
   unsigned char reversedNum = 0;
   unsigned char temp;
   
   int i = 0;

   // Reverse the first 4 bits
   for (; i < 4; i++) {
      temp = (num & (1 << i));
      if(temp)
         reversedNum |= (1 << ((4 - 1) - i));
   }

   // Copy the last 4 bits
   reversedNum |= (num & (0xF0));

   return reversedNum;
}

unsigned char getBitNumber(unsigned char byteToCount)
{
   unsigned char bitNumber;

   for(unsigned char i = 0; i < 7; i++)
   {
      bitNumber += ((byteToCount & (0x01 << i)) ? 1 : 0);
   }

   return bitNumber;
}

uint8_t countBits(uint8_t num) {
   uint8_t total = 0;

   for(uint8_t i = 0; i < 8; i++)
   {
      total += (num & (0x01 << i)) >> i;
   }

   return total;
}